language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: GY/KMaKY/JziFnpQTM+irfV0F5oyHH3MOgAwMGFNbbpSoH/LN6XmdK6eo7JEjfobHJDiGGQSeIsFAMWNVhZJ4gkVJKwiTz0g+l3Vf+YZPvCmxyZsDywr1ztZ9b7VicwEIf59RwjKiNU8s8bdtaqF0w/TX2FhLELWMZMr6/wBjpfRoUYCsL7VJOR9kTQzwyPgxj2+C0vVE5bpXB8W35+pDqYPEcHQis8jW5Z6lRsG4ST6NYjVV2w0QKxExTpp1SxCT2EubJKAETg4uL8cfGoaxyWsT37sN8LnWON6G21L0MK+/9zj7b2qFgYclf/efaMOsiK+gQoD/MbJOoihkRrgaq5wtl+2MdqRrSkT69acYMCwzhrHhtuyp+ucvBLxkcgmr3PMIzdmJs5NVAd19tcgL+EyYeR0RsBZ8gEt6Mug2/pifYs2DmRalpU+unHWvz4nkN8Z+SGPYfFCm37CXQR07rmIHbmUdmonccf6WomiFDblTVBQLbiv70DY6FLy6JdajBHWmnKtZFUwTIrftJFsVGUzkmMDOaNHx8AEkmzAXoWpgx8W4kEhxtnjo8C/JnwIb1DMlNeD5KlS0NfBzjFOr0UDTqcULFykiQProETsr72udJM4PeWEmwSz6313CdCEE5WgEMsLrdoOoGl32pBtVSOiWAGkdkQ583DCJUeiXOc=
  app: sup-template
  on:
    repo: 0e0/sup-template
    branch: staging
