language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: CtxJYTo+5GYqHnLAi87EtXbr835UxWsReb89ZNRCRtNspFeXfxaQtJ1P+PPk4MC7XU/iR55HpWOp2IuZRGuv/LchVT1ZOIfDcwSWIe3A6MhTahuhkB1xrRNSwGFqi3x8HuI06vwjPP41eRpr1c1hdhVl3qM6RmgnCv76NQFh+4Wb7c54tnWCK8Ox9wIG65Ii+7oNdqvUzRy/wq8YZrOvzBFwX8/7Sp2EChSNiUVhUMe6c9Fi/RFPbgdg3fBeE4DB0aAAoXhpLLM/fJuBpAE6/NF5IaIT1kcV1P871cXKVC7cl6+DQCiDLTW78NndedkxukUBl5OxHyCULo94iasJJNr0iV15wwH9WGioSVfwPLamA1j1AKGUOLIiDDNCb2ITcqnV1fadHvLbGU1LOBFGPpkfr2svy054gyVPTIiPxijBBef8TyW2Fgl4BDT6UMI46ZVIDJh/Vu/vaWZOzj5RRpWm0DLUVkKWkt9PrUmg0kRYJ6lnVQjb4KHxeZX7Rd0dkB5dpoiKHjenDjVQPMQ2Sgk7ckxw2AfZn/rtChF1spIm6l4h7Q4tWv804wgA/LkHpPCnC/lIwZkJ/cOajncvvaVgd4jswhE36ClXN9yq4/+pTp2vfCyqQjO6wx66FM8LXL+rJJqi7Oo/gQ+7gL2dYZbZx0bvaJpaT1E+CR8PTPI=
  app: sup-template
  on:
    repo: 0e0/sup-template
    branch: staging
