language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: MllFMMYSQsTHUP7EZ8QYLfGp2Z9FOBXAWQAESaxK9GMvwNwuJl1d/IGQ1Sf9ef0fdQcaWXMluSgegwYcYiJJOTyhoKce5BgqcaumEp6QwVgjY+jxcPUsn8Li6BS9vvKSCipNaid8h7HuREL/PbqBxVlWRVyLBmP23Xm6AjUKY7V1SOM9ze+GiheubaHWh0/VlQ/oqeD8tPFGkd3l8MzqeP2KSlbSkKdOoEcYTtozYrgBS0iLS5+jhgEq0zZfJz66vspVHde2TuhyKBXFMaZ2fJ/lVH+MG1l2W4oh/8+MKwwO0K6ZS4Kq4IM7hw/94+n/PNsi66sroNMrTpnRJXqjadYhyDiPqVRgueaLVt7+5rydd7DQixatImZvJYTa3+JH9Po7LDhQayaQnfLxRxB9Vs+jAZkekZxrJ/dPwzQlDhonFmRx4ZBHaxwW/vrSG2NrDTUWaSwxorxaNIXtb7eytZMJbIu2DnU9Jeu27yhEE7ypKPlc7Xk21nZ1+rwVRT5dGqrG10DNfHltGHvTj4zNSZhnNR6A/AScwOW3rLm9E9yyhtjGaUVwciC/xvQQeQxFJk3b0iQIo6+4J1FHnadG2wB4ohbI0jarqDkWwV3osLQgpAlqkK+2pmjaeYcNjVgNIIjbc7JWtsTt9lNa998wHEcfDShCPRYFueupdRn2bW0=
  app: sup-template
  on:
    repo: 0e0/sup-template
    branch: staging
