language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: kI6+llZzXZSmLDIIX2VtyI19d0w1sQap+b0kvOr8evKnLaZhNDXirMP9MR8x47MqnLum5+EOAzFi3UtqwThBUrjjwgH4YbRJ2DKKIEweXhXz8EtbA5XQGniaFbo7ayBkt5VPFRF0OPCj+TY8Y+H9De5FQNOEXW4pFLy/K5Iko50ilGM5RAXLH0cnmE0qWAMvWHtnC3lQrsD677pu0o8pcNWhDJp8OSzmtLvdfi1oQlnUe97RBM/M1i+CWJtVbZ9lUyBqyKjH762Xb4hlkoq6fyijLbaTMIHIS78YtFSI/vgucMXSog427XjQzuMWlb236ZAsNt8AZZkIfkExGVe0nbiwgfx5NSGpjLDCHf6eGOBehtOh9OaD5FWE9YTA8hiUvdTDhzt3xr2X/PF60Ibht1KqLLqCVagH4eSBRBAzyLBdGL0xaSA17/GEzHvVPjRLyz9cIWsQcRNSVVHZVIcgPVs4oaQ6oF7yMqbWfRnuHmH3pSv5M7RVkSJA54QvwgUG+68drhL3g0YakD639AxkRxnt0WaqfOtBMPWGWvCQdBYmmIcF4BWYsVz8GlBX8scolmLSmSkdRNeTCCrhRdxTHbDRKQkr1xvubA/8YheE/zcrQuaE5uRzMMnjOmXwVZZiu90NvRhgHt88Ndt6RvhARgvbBZ3uwFmbAWogYYcg70E=
  app: sup-template
  on:
    repo: 0e0/sup-template
    branch: staging
